name: "CICD SSH Logs attemps"
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-ec2:
    name: "Ubuntu EC2"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Configuration SSH
        env:
         SSH_USER: ${{ secrets.SSH_USER }}
         SSH_KEY: ${{ secrets.SSH_PEM }}
         SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/gcp.pem
          chmod 400 ~/.ssh/gcp.pem
          cat >> ~/.ssh/config << END
          Host Deployment
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/gcp.pem
            StrictHostKeyChecking=no
          END
      - name: Connect Compute Engine
        run: ssh development || true
      - name: Move directory git repo
        run: touch widi-githubaction
