name: "CICD SSH Logs attemps"
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-ec2:
    name: "Deploy to ec2 from registry docker hub"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configuration SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/gcp.pem
          chmod 400 ~/.ssh/gcp.pem
          cat >>~/.ssh/config <<END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/gcp.pem
            StrictHostKeyChecking=no
          END
      - name: Connect EC2 & Remove All Container & Pull from Registry & Start
        run: ssh development 'docker pull aprian1337/thukul'

