name: "CICD SSH Logs attemps"
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-ec2:
    name: "Deploy to ec2 from registry docker hub"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configuration SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          ID_RSA : ${{ secrets.ID_RSA  }}
          ID_RSA_PUB: ${{ secrets.ID_RSA_PUB }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ID_RSA" > ~/.ssh/id_rsa
          echo "$ID_RSA_PUB" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          cat >>~/.ssh/config <<END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/gcp.pem
            StrictHostKeyChecking=no
          END
      - name: Connect EC2 & Remove All Container & Pull from Registry & Start
        run: ssh development 'touch widi-gitaction'

